spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  servlet:
    session:
      cookie:
        name: JSESSIONID
        http-only: false  # Permite acesso via JavaScript (para desenvolvimento)
        secure: false     # Permite cookies em HTTP (não apenas HTTPS)
        same-site: lax    # Configuração de segurança para cookies