spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html

jwt:
  secret: ${JWT_SECRET}
  expiration: 28800000
  token-prefix: Bearer
  header: Authorization

logging:
  level:
    root: INFO # nível geral do sistema
    org.springframework.web: DEBUG # logs do Spring Web (request, dispatch etc)
    org.springframework.security: DEBUG # logs do Spring Security (autenticação, autorização)
    com.api.cuida: DEBUG # logs da sua aplicação (pacote base)

